name: Build Backend

on:
  push:
    branches: [develop, master]

  workflow_dispatch:

env:
  DOCKER_SERVER: registry.cn-hangzhou.aliyuncs.com
  DOCKER_NAMESPACE: neal2034
  DOCKER_REPOSITORY: todo-backend

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    if: contains(github.event.commits[0].message, 'skip build') == false
    outputs:
      image: ${{ steps.set-image.outputs.image }}
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - uses: actions/checkout@v3

      - uses: docker/metadata-action@v4
        id: meta
        with:
          flavor: latest=false
          images: |
            ${{ env.DOCKER_SERVER }}/${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_REPOSITORY }}
          tags: |
            type=semver,pattern={{ version }}
            type=raw,value=production,enable=true

      - name: Set Image
        id: set-image
        run: |
          echo "image=${{ env.DOCKER_SERVER }}/${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_REPOSITORY }}:${{ steps.meta.outputs.version }}" >> $GITHUB_OUTPUT

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - uses: actions/checkout@v3
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          login-server: ${{ env.DOCKER_SERVER }}

      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          push: true
          provenance: false
          context: .
          file: ./Dockerfile
          tags: ${{ needs.prepare.outputs.tags }}
          cache-from: type=gha,scope=backend
          cache-to: type=gha,scope=backend,mode=max

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [prepare, build]
    steps:
      - uses: actions/checkout@v3
      - name: Compose Docker Command
        uses: neal2034/gitactions/docker-run-cmd@master
        id: docker
        with:
          name: todo-backend
          image: ${{ needs.prepare.outputs.image }}
          envfile: /root/backend_envs/todo/todo_env
          post-start: sleep 2 && docker exec phoenix-nginx  nginx -s reload

      - name: Deploy
        uses: neal2034/gitactions/ssh-action@master
        with:
          dryrun: false
          key: ${{ secrets.DEV_HOST_PRIVATE_KEY }}
          nodes: ${{ secrets.DEV_HOST }}
          node-index: 0
          script: ${{ steps.docker.outputs.cmd }}

      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        if: ${{ job.status }} != 'skipped'
        env:
          SLACK_WEBHOOK_URL: ${{  secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          author_name: Notify
